{% set version = "0.1.0" %}

package:
  name: varys
  version: {{ version }}

source:
  url: 
  sha256: 

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6

  run:
    - python >=3.6
    - pika >=1.3.0
    - setuptools >=42

about:
  home: 
  license: GNU GPLv3
  summary: 'varys: a RabbitMQ python client, master of whispers for CLIMB-TRE'
  license_family: GPL